"""create relationship book and user

Revision ID: 75dd77c82566
Revises: 91aeaad58242
Create Date: 2024-10-24 15:09:15.203172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '75dd77c82566'
down_revision: Union[str, None] = '91aeaad58242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uid', sa.UUID(), nullable=True, foreign_key='users.uid'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'user_uid')
    # ### end Alembic commands ###
